# get into area
self.keyboard.keyDown("a")
sleep(1)
self.keyboard.keyUp("a")
self.keyboard.keyDown("w")
sleep(3)
self.keyboard.keyUp("w")
self.keyboard.keyDown("s")
sleep(0.77)
self.keyboard.keyUp("s")
self.keyboard.keyDown("d")
sleep(1.8)
self.keyboard.press("space")
sleep(5)
self.keyboard.keyUp("d")
#back right corner
self.keyboard.keyDown("s")
sleep(5)
self.keyboard.keyUp("s")
sleep(7)
#credit to rubicorb.v2 for the path